### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by andyihsan** [FeezyHendrix/Insta-mass-account-creator#30]
{'error_type': 'signup_block', 'status': 'ok', 'account_created': False, 'errors': {'ip': ['The IP address you are using has been flagged as an open proxy. If you believe this to be incorrect, please visit http://help.instagram.com/']}}

why? I have used a proxy, usually your script old & need fixed

**Comment by FeezyHendrix** [comment]
Try using the selenium bot

**Comment by andyihsan** [comment]
how to run selenium in python?

**Comment by andyihsan** [comment]
not working again

**Comment by FeezyHendrix** [comment]
What's the error message you are receive while using the selenium bot?

**Comment by andyihsan** [comment]
how to run selenium in python?

**Comment by andyihsan** [comment]
i try python again ehhehe

**Comment by YangMin** [comment]
I have same problem when I use the request bot.  
I think the reason is the headers. The headers should be changed every time. Such as **user-agent,x-csrftoken,x-instagram-ajax.** 
But I do not know how to gengerate 'x-instagram-ajax' and 'csrftoken'.

Who can help me? I think if the problem resoved, the bot will be perfect. otherwisel the bot has no value.
